/*
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The wallet subtype of the Delegate. Possible values include: - &#x60;Org-Controlled&#x60;: MPC Wallets (Organization-Controlled Wallets). - &#x60;User-Controlled&#x60;: MPC Wallets (User-Controlled Wallets). 
 */
@JsonAdapter(CoboSafeDelegateType.Adapter.class)
public enum CoboSafeDelegateType {
  UNKNOWN(null),
  
  ORG_CONTROLLED("Org-Controlled"),
  
  USER_CONTROLLED("User-Controlled");

  private String value;

  CoboSafeDelegateType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CoboSafeDelegateType fromValue(String value) {
    for (CoboSafeDelegateType b : CoboSafeDelegateType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CoboSafeDelegateType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CoboSafeDelegateType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CoboSafeDelegateType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CoboSafeDelegateType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CoboSafeDelegateType.fromValue(value);
  }
}

