/*
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.TransactionUtxo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * The raw transaction information.
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class TransactionRawTxInfo {
  public static final String SERIALIZED_NAME_USED_NONCE = "used_nonce";
  @SerializedName(SERIALIZED_NAME_USED_NONCE)
  private Integer usedNonce;

  public static final String SERIALIZED_NAME_SELECTED_UTXOS = "selected_utxos";
  @SerializedName(SERIALIZED_NAME_SELECTED_UTXOS)
  private List<TransactionUtxo> selectedUtxos = new ArrayList<>();

  public static final String SERIALIZED_NAME_RAW_TX = "raw_tx";
  @SerializedName(SERIALIZED_NAME_RAW_TX)
  private String rawTx;

  public TransactionRawTxInfo() {
  }

  public TransactionRawTxInfo usedNonce(Integer usedNonce) {
    this.usedNonce = usedNonce;
    return this;
  }

   /**
   * The transaction nonce.
   * @return usedNonce
  **/
  @javax.annotation.Nullable
  public Integer getUsedNonce() {
    return usedNonce;
  }

  public void setUsedNonce(Integer usedNonce) {
    this.usedNonce = usedNonce;
  }


  public TransactionRawTxInfo selectedUtxos(List<TransactionUtxo> selectedUtxos) {
    this.selectedUtxos = selectedUtxos;
    return this;
  }

  public TransactionRawTxInfo addSelectedUtxosItem(TransactionUtxo selectedUtxosItem) {
    if (this.selectedUtxos == null) {
      this.selectedUtxos = new ArrayList<>();
    }
    this.selectedUtxos.add(selectedUtxosItem);
    return this;
  }

   /**
   * The selected UTXOs to be consumed in the transaction.
   * @return selectedUtxos
  **/
  @javax.annotation.Nullable
  public List<TransactionUtxo> getSelectedUtxos() {
    return selectedUtxos;
  }

  public void setSelectedUtxos(List<TransactionUtxo> selectedUtxos) {
    this.selectedUtxos = selectedUtxos;
  }


  public TransactionRawTxInfo rawTx(String rawTx) {
    this.rawTx = rawTx;
    return this;
  }

   /**
   * The raw transaction data.
   * @return rawTx
  **/
  @javax.annotation.Nullable
  public String getRawTx() {
    return rawTx;
  }

  public void setRawTx(String rawTx) {
    this.rawTx = rawTx;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TransactionRawTxInfo instance itself
   */
  public TransactionRawTxInfo putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionRawTxInfo transactionRawTxInfo = (TransactionRawTxInfo) o;
    return Objects.equals(this.usedNonce, transactionRawTxInfo.usedNonce) &&
        Objects.equals(this.selectedUtxos, transactionRawTxInfo.selectedUtxos) &&
        Objects.equals(this.rawTx, transactionRawTxInfo.rawTx)&&
        Objects.equals(this.additionalProperties, transactionRawTxInfo.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usedNonce, selectedUtxos, rawTx, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionRawTxInfo {\n");
    sb.append("    usedNonce: ").append(toIndentedString(usedNonce)).append("\n");
    sb.append("    selectedUtxos: ").append(toIndentedString(selectedUtxos)).append("\n");
    sb.append("    rawTx: ").append(toIndentedString(rawTx)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("used_nonce");
    openapiFields.add("selected_utxos");
    openapiFields.add("raw_tx");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TransactionRawTxInfo
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransactionRawTxInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TransactionRawTxInfo is not found in the empty JSON string", TransactionRawTxInfo.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("selected_utxos") != null && !jsonObj.get("selected_utxos").isJsonNull()) {
        JsonArray jsonArrayselectedUtxos = jsonObj.getAsJsonArray("selected_utxos");
        if (jsonArrayselectedUtxos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("selected_utxos").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `selected_utxos` to be an array in the JSON string but got `%s`", jsonObj.get("selected_utxos").toString()));
          }

          // validate the optional field `selected_utxos` (array)
          for (int i = 0; i < jsonArrayselectedUtxos.size(); i++) {
            TransactionUtxo.validateJsonElement(jsonArrayselectedUtxos.get(i));
          };
        }
      }
      if ((jsonObj.get("raw_tx") != null && !jsonObj.get("raw_tx").isJsonNull()) && !jsonObj.get("raw_tx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `raw_tx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("raw_tx").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransactionRawTxInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransactionRawTxInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransactionRawTxInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransactionRawTxInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<TransactionRawTxInfo>() {
           @Override
           public void write(JsonWriter out, TransactionRawTxInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TransactionRawTxInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             TransactionRawTxInfo instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TransactionRawTxInfo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TransactionRawTxInfo
  * @throws IOException if the JSON string is invalid with respect to TransactionRawTxInfo
  */
  public static TransactionRawTxInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransactionRawTxInfo.class);
  }

 /**
  * Convert an instance of TransactionRawTxInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

