/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The transaction result type. Possible values include:   - &#x60;Signature&#x60;: An EVM EIP-191 or EVM EIP-712 signature. 
 */
@JsonAdapter(TransactionResultType.Adapter.class)
public enum TransactionResultType {
  UNKNOWN(null),
  
  SIGNATURE("Signature");

  private String value;

  TransactionResultType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TransactionResultType fromValue(String value) {
    for (TransactionResultType b : TransactionResultType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TransactionResultType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TransactionResultType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TransactionResultType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TransactionResultType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TransactionResultType.fromValue(value);
  }
}

