/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.EstimatedEvmEip1559Fee;
import com.cobo.waas2.model.EstimatedEvmLegacyFee;
import com.cobo.waas2.model.EstimatedFixedFee;
import com.cobo.waas2.model.EstimatedUtxoFee;
import com.cobo.waas2.model.EstimatedUtxoFeeSlow;
import com.cobo.waas2.model.FeeType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EstimatedFee
 */
public class EstimatedFeeTest {
    private final EstimatedFee model = new EstimatedFee();

    /**
     * Model tests for EstimatedFee
     */
    @Test
    public void testEstimatedFee() {
        // TODO: test EstimatedFee
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'isLoop'
     */
    @Test
    public void isLoopTest() {
        // TODO: test isLoop
    }

    /**
     * Test the property 'feeAmount'
     */
    @Test
    public void feeAmountTest() {
        // TODO: test feeAmount
    }

    /**
     * Test the property 'slow'
     */
    @Test
    public void slowTest() {
        // TODO: test slow
    }

    /**
     * Test the property 'recommended'
     */
    @Test
    public void recommendedTest() {
        // TODO: test recommended
    }

    /**
     * Test the property 'fast'
     */
    @Test
    public void fastTest() {
        // TODO: test fast
    }

}
