/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.ActivityType;
import com.cobo.waas2.model.CreateStakeActivityExtra;
import com.cobo.waas2.model.EstimateStakeFee;
import com.cobo.waas2.model.EstimateUnstakeFee;
import com.cobo.waas2.model.EstimateWithdrawFee;
import com.cobo.waas2.model.StakingSource;
import com.cobo.waas2.model.TransactionRequestFee;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetStakingEstimationFeeRequest
 */
public class GetStakingEstimationFeeRequestTest {
    private final GetStakingEstimationFeeRequest model = new GetStakingEstimationFeeRequest();

    /**
     * Model tests for GetStakingEstimationFeeRequest
     */
    @Test
    public void testGetStakingEstimationFeeRequest() {
        // TODO: test GetStakingEstimationFeeRequest
    }

    /**
     * Test the property 'activityType'
     */
    @Test
    public void activityTypeTest() {
        // TODO: test activityType
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'poolId'
     */
    @Test
    public void poolIdTest() {
        // TODO: test poolId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'stakingId'
     */
    @Test
    public void stakingIdTest() {
        // TODO: test stakingId
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

}
