/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.KeyShareHolderStatus;
import com.cobo.waas2.model.KeyShareHolderType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for KeyShareHolder
 */
public class KeyShareHolderTest {
    private final KeyShareHolder model = new KeyShareHolder();

    /**
     * Model tests for KeyShareHolder
     */
    @Test
    public void testKeyShareHolder() {
        // TODO: test KeyShareHolder
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'tssNodeId'
     */
    @Test
    public void tssNodeIdTest() {
        // TODO: test tssNodeId
    }

    /**
     * Test the property 'online'
     */
    @Test
    public void onlineTest() {
        // TODO: test online
    }

    /**
     * Test the property 'signer'
     */
    @Test
    public void signerTest() {
        // TODO: test signer
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

}
