/*
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LockUtxos201Response
 */
public class LockUtxos201ResponseTest {
    private final LockUtxos201Response model = new LockUtxos201Response();

    /**
     * Model tests for LockUtxos201Response
     */
    @Test
    public void testLockUtxos201Response() {
        // TODO: test LockUtxos201Response
    }

    /**
     * Test the property 'executed'
     */
    @Test
    public void executedTest() {
        // TODO: test executed
    }

}
