/*
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.WalletSubtype;
import com.cobo.waas2.model.WalletType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PoolSummary
 */
public class PoolSummaryTest {
    private final PoolSummary model = new PoolSummary();

    /**
     * Model tests for PoolSummary
     */
    @Test
    public void testPoolSummary() {
        // TODO: test PoolSummary
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'protocol'
     */
    @Test
    public void protocolTest() {
        // TODO: test protocol
    }

    /**
     * Test the property 'protocolIconUrl'
     */
    @Test
    public void protocolIconUrlTest() {
        // TODO: test protocolIconUrl
    }

    /**
     * Test the property 'supportedWalletTypes'
     */
    @Test
    public void supportedWalletTypesTest() {
        // TODO: test supportedWalletTypes
    }

    /**
     * Test the property 'supportedWalletSubtypes'
     */
    @Test
    public void supportedWalletSubtypesTest() {
        // TODO: test supportedWalletSubtypes
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'estApr'
     */
    @Test
    public void estAprTest() {
        // TODO: test estApr
    }

}
