/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TokenBalanceBalance;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubWalletAssetBalance
 */
public class SubWalletAssetBalanceTest {
    private final SubWalletAssetBalance model = new SubWalletAssetBalance();

    /**
     * Model tests for SubWalletAssetBalance
     */
    @Test
    public void testSubWalletAssetBalance() {
        // TODO: test SubWalletAssetBalance
    }

    /**
     * Test the property 'tradingAccountType'
     */
    @Test
    public void tradingAccountTypeTest() {
        // TODO: test tradingAccountType
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

}
