/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenInfo
 */
public class TokenInfoTest {
    private final TokenInfo model = new TokenInfo();

    /**
     * Model tests for TokenInfo
     */
    @Test
    public void testTokenInfo() {
        // TODO: test TokenInfo
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'decimal'
     */
    @Test
    public void decimalTest() {
        // TODO: test decimal
    }

    /**
     * Test the property 'iconUrl'
     */
    @Test
    public void iconUrlTest() {
        // TODO: test iconUrl
    }

    /**
     * Test the property 'tokenAddress'
     */
    @Test
    public void tokenAddressTest() {
        // TODO: test tokenAddress
    }

    /**
     * Test the property 'feeTokenId'
     */
    @Test
    public void feeTokenIdTest() {
        // TODO: test feeTokenId
    }

    /**
     * Test the property 'canDeposit'
     */
    @Test
    public void canDepositTest() {
        // TODO: test canDeposit
    }

    /**
     * Test the property 'canWithdraw'
     */
    @Test
    public void canWithdrawTest() {
        // TODO: test canWithdraw
    }

}
