/*
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.FeeType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionUtxoFee
 */
public class TransactionUtxoFeeTest {
    private final TransactionUtxoFee model = new TransactionUtxoFee();

    /**
     * Model tests for TransactionUtxoFee
     */
    @Test
    public void testTransactionUtxoFee() {
        // TODO: test TransactionUtxoFee
    }

    /**
     * Test the property 'feeRate'
     */
    @Test
    public void feeRateTest() {
        // TODO: test feeRate
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'feeUsed'
     */
    @Test
    public void feeUsedTest() {
        // TODO: test feeUsed
    }

    /**
     * Test the property 'maxFeeAmount'
     */
    @Test
    public void maxFeeAmountTest() {
        // TODO: test maxFeeAmount
    }

}
