/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.FeeType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionRequestEvmEip1559Fee
 */
public class TransactionRequestEvmEip1559FeeTest {
    private final TransactionRequestEvmEip1559Fee model = new TransactionRequestEvmEip1559Fee();

    /**
     * Model tests for TransactionRequestEvmEip1559Fee
     */
    @Test
    public void testTransactionRequestEvmEip1559Fee() {
        // TODO: test TransactionRequestEvmEip1559Fee
    }

    /**
     * Test the property 'maxFeePerGas'
     */
    @Test
    public void maxFeePerGasTest() {
        // TODO: test maxFeePerGas
    }

    /**
     * Test the property 'maxPriorityFeePerGas'
     */
    @Test
    public void maxPriorityFeePerGasTest() {
        // TODO: test maxPriorityFeePerGas
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'gasLimit'
     */
    @Test
    public void gasLimitTest() {
        // TODO: test gasLimit
    }

}
