/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.CustodialWalletInfo;
import com.cobo.waas2.model.ExchangeId;
import com.cobo.waas2.model.ExchangeWalletInfo;
import com.cobo.waas2.model.MPCWalletInfo;
import com.cobo.waas2.model.SmartContractInitiator;
import com.cobo.waas2.model.SmartContractWalletInfo;
import com.cobo.waas2.model.SmartContractWalletType;
import com.cobo.waas2.model.WalletSubtype;
import com.cobo.waas2.model.WalletType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WalletInfo
 */
public class WalletInfoTest {
    private final WalletInfo model = new WalletInfo();

    /**
     * Model tests for WalletInfo
     */
    @Test
    public void testWalletInfo() {
        // TODO: test WalletInfo
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    public void walletIdTest() {
        // TODO: test walletId
    }

    /**
     * Test the property 'walletType'
     */
    @Test
    public void walletTypeTest() {
        // TODO: test walletType
    }

    /**
     * Test the property 'walletSubtype'
     */
    @Test
    public void walletSubtypeTest() {
        // TODO: test walletSubtype
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'orgId'
     */
    @Test
    public void orgIdTest() {
        // TODO: test orgId
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'vaultId'
     */
    @Test
    public void vaultIdTest() {
        // TODO: test vaultId
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'smartContractWalletType'
     */
    @Test
    public void smartContractWalletTypeTest() {
        // TODO: test smartContractWalletType
    }

    /**
     * Test the property 'safeAddress'
     */
    @Test
    public void safeAddressTest() {
        // TODO: test safeAddress
    }

    /**
     * Test the property 'signers'
     */
    @Test
    public void signersTest() {
        // TODO: test signers
    }

    /**
     * Test the property 'threshold'
     */
    @Test
    public void thresholdTest() {
        // TODO: test threshold
    }

    /**
     * Test the property 'coboSafeAddress'
     */
    @Test
    public void coboSafeAddressTest() {
        // TODO: test coboSafeAddress
    }

    /**
     * Test the property 'initiator'
     */
    @Test
    public void initiatorTest() {
        // TODO: test initiator
    }

    /**
     * Test the property 'apikey'
     */
    @Test
    public void apikeyTest() {
        // TODO: test apikey
    }

    /**
     * Test the property 'exchangeId'
     */
    @Test
    public void exchangeIdTest() {
        // TODO: test exchangeId
    }

    /**
     * Test the property 'mainWalletId'
     */
    @Test
    public void mainWalletIdTest() {
        // TODO: test mainWalletId
    }

}
